### PR TITLE
Make cropper RGB friendly, N-dimensional, and sliceable from any orthogonal viewpoint

### PR DESCRIPTION
**Pull request by tdmorello**
Hi Robert,

First of all, consider me a big fan of your napari plugins -- I really appreciate the number of tools you are creating and publishing for napari users!

Second, I was testing out this plugin and found it wasn't working on RGB images, so I dug into the code a little bit and thought of some ways to (hopefully) make it applicable to more scenarios. If you get some time to test it out, I'd really appreciate it!

I think the key features are:
1) it works with _any_ number of dimensions
2) you can draw a cropping region in an orthogonal view (e.g. XZ plane) and it'll give you the expected results
3) the slice indices aren't hard-coded, so it should be a little easier to maintain and adapt

I also wrote some tests to help my dev'ing (and hope they will be useful to the repo as well).

Finally, I see @zoccoler 's PR and am planning on trying to fit my changes in with his (polygon cropping). The code I'm sharing can be easily modified to output more than 1 new layer when multiple shapes are draw. 

Let me know what you think.

Best,
Tim

### CODE REVIEW

**Comment by tdmorello** [comment]
I forgot to add -- this version handles shapes with vertices that extend below (0, 0) or beyond the max image shape by adjusting the crop region to fit within the image dimensions.

**Comment by haesleinhuepf** [comment]
Hi Tim @tdmorello ,

wow, thanks for this amazing Christmas present! I just tested your version in napari and it works great! 

You did quite some super cool modifications to the code. I like how you deal with `layer_props` (I wasn't aware that one can copy properties of layers like this) and the tests are also super cool.

I would take the failing tests in the github CI on my todo list. 

However, only 18 out of 22 tests run locally on my machine. I receive errors like this one:

```
_________________________________________ test_crop_function_nd[poly_crop-6D] _________________________________________

image_data = array([[[[[[5.99292016e-01, 2.75542806e-01, 8.82586784e-01, ...,
            4.57794413e-01, 4.55699337e-01, 4.3980948...[9.05130255e-01, 2.80591673e-01, 5.97141497e-01, ...,
            5.68965809e-01, 4.37007750e-01, 7.44631706e-01]]]]]])
rgb = False
shape_data = array([[0, 0, 0, 0, 0, 2],
       [4, 0, 0, 0, 0, 4],
       [4, 0, 0, 0, 0, 2],
       [2, 0, 0, 0, 0, 0]])
shape_type = 'polygon', make_napari_viewer = <function make_napari_viewer.<locals>.actual_factory at 0x0000022D293FA310>

    @pytest.mark.parametrize("image_data,rgb", image_data, ids=image_data_ids)
    @pytest.mark.parametrize(
        "shape_data,shape_type", zip(shape_data, shape_types), ids=shape_data_ids
    )
    def test_crop_function_nd(image_data, rgb, shape_data, shape_type, make_napari_viewer):
        viewer = make_napari_viewer()

        img_layer = viewer.add_image(image_data, rgb=rgb)

        # shape data is (N,D) array where N is num verts and D is num dims
        diff_dims = image_data.ndim - shape_data.shape[1]
        # if rgb:
        #     diff_dims -= 1
        shape_data = np.insert(shape_data, [-1], np.zeros(diff_dims), axis=1)
        shp_layer = viewer.add_shapes(shape_data, shape_type=shape_type)

        nlayers = len(viewer.layers)
>       viewer.add_layer(crop_region(img_layer, shp_layer))

napari_crop\_tests\test_function.py:87:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
napari_crop\_function.py:68: in crop_region
    mask = np.broadcast_to(mask2D, cropped_data.shape)
<__array_function__ internals>:5: in broadcast_to
    ???
C:\Users\rober\miniconda3\envs\nap-dev-bio2\lib\site-packages\numpy\lib\stride_tricks.py:411: in broadcast_to
    return _broadcast_to(array, shape, subok=subok, readonly=True)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

array = array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])
shape = (2, 2, 2, 2, 8, 5), subok = False, readonly = True

    def _broadcast_to(array, shape, subok, readonly):
        shape = tuple(shape) if np.iterable(shape) else (shape,)
        array = np.array(array, copy=False, subok=subok)
        if not shape and array.shape:
            raise ValueError('cannot broadcast a non-scalar to a scalar array')
        if any(size < 0 for size in shape):
            raise ValueError('all elements of broadcast shape must be non-'
                             'negative')
        extras = []
>       it = np.nditer(
            (array,), flags=['multi_index', 'refs_ok', 'zerosize_ok'] + extras,
            op_flags=['readonly'], itershape=shape, order='C')
E       ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (3,5)  and requested shape (2,2,2,2,8,5)

C:\Users\rober\miniconda3\envs\nap-dev-bio2\lib\site-packages\numpy\lib\stride_tricks.py:348: ValueError
```

Otherwise, when this error is fixed, I could merge this as it is. You could then send another PR together with Marcelo @zoccoler's modifications, or shall we wait until you modified this PR? I'm happy to do this as you prefer.

Big thanks again! It's a pleasure working with you :-)

Happy Holidays!

Best,
Robert

**Comment by tdmorello** [comment]
My mistake! I forgot to create a new branch after the PR.

It should be fixed now.

Happy holidays!

**Comment by tdmorello** [comment]
Hey @haesleinhuepf

I managed to get @zoccoler 's idea working in N dimensions and with RGB(A)

Hope it's helpful!

**Comment by haesleinhuepf** [comment]
Hi @tdmorello ,

thanks again! I'll test soon and might merge then immediately. I was just wondering, as you now wrote half of the code, do you want to be part of the author-list [here](https://github.com/haesleinhuepf/napari-crop/blob/main/setup.cfg#L4) and [here](https://github.com/haesleinhuepf/napari-crop/blob/main/LICENSE#L2)? I would be happy to welcome you and it comes with no commitments. It's just to give credit where credit is due. And you improved our code quite a lot!

Thanks again!

**Comment by tdmorello** [comment]
Thanks for the thoughtful author invite @haesleinhuepf ! I updated those files.

P.S. I just registered for the napari hackathon on the 13th. Maybe I'll see you there!

**Comment by haesleinhuepf** [comment]
Awesome, thanks!

> P.S. I just registered for the napari hackathon on the 13th. Maybe I'll see you there!

I hope you mean the hackathon on the 18th. If so, I'm looking forward to meeting you there!

**Pull request merged**
