### PR TITLE
Crop all shapes

### PR DESCRIPTION
**Pull request by zoccoler**
Hi Robert @haesleinhuepf 

I modified the function adding 2 new functionalities:
1.  if more than one shape is drawn in the layer shape, it crops all shapes and adds them as new layers;
2.  if the shapes have irregular shapes (like ellipses or polygons), it crops according to that shape, clearing pixels outside the shape;
- I also changed a little the extent of the shapes position and size (from `.astype(int)` to `np.ceil` or `np.around`) to ensure the irregular drawn shape would be entirely captured;

Please let me know if it works and if you have suggestions/improvements to the code 😃

### CODE REVIEW

**Review by haesleinhuepf — APPROVED** [review]
Hi Marcelo @zoccoler,

thanks for the cool new features here! I would merge them if you think they are ready (it's a PR-draft yet). 
Also feel free to add yourself to the [author list of this plugin](https://github.com/haesleinhuepf/napari-crop/blob/main/setup.cfg#L4). We can also discuss in the next group meeting if this plugin should become part of github.com/biapol/ .

Happy Holidays!
Robert

**Comment by zoccoler** [comment]
Hi Robert @haesleinhuepf ,

I cannot merge myself because it says it needs [workflow run approval](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks) by the maintainer. Please check if you can do this and I can merge afterwards.

Best,
Marcelo

**Comment by haesleinhuepf** [comment]
Hi Marcelo @zoccoler ,

as you may have noticed, Tim @tdmorello was so kind and incorporated your changes in his PR #3 . Hence, I won't merge this PR here. Would you mind checking if it works for your use-cases? If not, please open an issue. 

Thanks!
Robert

**Comment by zoccoler** [comment]
Hi Robert @haesleinhuepf ,

Sure ! Thank you @tdmorello ! I will test right away and let you know! :)

Best,
Marcelo

**Pull request closed without merging**
